Repository Leafwing-Studios/leafwing_manifest, pull requests merged in 2024-04, with the labels that each got.

#17 Add CI
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/code-quality.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/usability.md
  .github/PULL_REQUEST_TEMPLATE/pr.md
  .github/dependabot.yml
  .github/linters/.markdown-lint.yml
  .github/linters/markdown-link-check.json
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  src/identifier.rs
  src/manifest.rs
  src/plugin.rs
  tools/ci/Cargo.toml
  tools/ci/src/main.rs
Labels: build system

#25 Initial draft of the entities-from-manifests example
  assets/tiles.ron
  examples/entities_from_manifests.rs
  src/plugin.rs
Labels: documentation

#31 Use OnEnter schedules correctly
  examples/raw_manifest.rs
  examples/simple.rs
Labels: documentation

#33 Allow users to opt out of automatically advancing asset state
  src/plugin.rs
Labels: usability

#32 Rename AppExt to RegisterManifest
  examples/entities_from_manifests.rs
  examples/raw_manifest.rs
  examples/simple.rs
  src/plugin.rs
Labels: usability

#30 Add custom_asset_loading example
  examples/custom_asset_lifecycle.rs
  examples/custom_asset_lifecycles.rs
Labels: documentation

#36 Remove examples that won't make it to 0.1
  examples/dynamic_manifest.rs
  examples/item_crossreferencing.rs
  examples/manifest_editors.rs
  examples/split_manifests.rs
Labels: documentation

#37 Complete items_by_name example
  examples/items_by_name.rs
  src/manifest.rs
Labels: documentation, usability
